name: .NET CI

on:
  push:
    branches: [ "master", "build-packaging" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Autometrics-CS.sln
    - name: Build
      run: dotnet build Autometrics-CS.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test Autometrics-CS.sln --verbosity normal --configuration Release --logger "nunit"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json