name: .NET CI

on:
  push:
    branches: [ "master", "build-automation" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Autometrics-CS.sln
    - name: Build
      run: dotnet build Autometrics-CS.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test Autometrics-CS.sln --verbosity normal --configuration Release --logger "nunit"
    - name: Convert Test Results
      run: docker run --rm -v$PWD:/app -w/app sverrirab/nunit3-junit-xml-transformer TestResults.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: TestResults.xml
